/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bah.app;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class CustomerApp {
    public static void main(String[] args) {
	SpringApplication.run(CustomerApp.class,args);
}}
